// Generated by bun-plugin-auto-imports
//
// Name to file, relative to this file. The resolvers read it, and the name
// types are `keyof` over it - so a name that type-checks is a name that
// resolves. Values are paths rather than import thunks on purpose: thunks
// would make every compilation that touches a name resolve every module.
export const emails = {
  'Welcome': '../../../resources/emails/Welcome.stx',
  'email-verification': '../../../node_modules/@stacksjs/defaults/resources/emails/email-verification.stx',
  'password-changed': '../../../node_modules/@stacksjs/defaults/resources/emails/password-changed.stx',
  'password-reset': '../../../node_modules/@stacksjs/defaults/resources/emails/password-reset.stx',
  'subscription-confirmation': '../../../node_modules/@stacksjs/defaults/resources/emails/subscription-confirmation.stx',
  'team-invitation': '../../../node_modules/@stacksjs/defaults/resources/emails/team-invitation.stx',
  'welcome': '../../../node_modules/@stacksjs/defaults/resources/emails/welcome.stx',
  'layouts/base': '../../../node_modules/@stacksjs/defaults/resources/emails/layouts/base.html',
} as const
