// Generated by bun-plugin-auto-imports
//
// Name to file, relative to this file. The resolvers read it, and the name
// types are `keyof` over it - so a name that type-checks is a name that
// resolves. Values are paths rather than import thunks on purpose: thunks
// would make every compilation that touches a name resolve every module.
export const middleware = {
  'Abilities': '../../../node_modules/@stacksjs/defaults/app/Middleware/Abilities.ts',
  'Api': '../../../node_modules/@stacksjs/defaults/app/Middleware/Api.ts',
  'Auth': '../../../node_modules/@stacksjs/defaults/app/Middleware/Auth.ts',
  'Can': '../../../node_modules/@stacksjs/defaults/app/Middleware/Can.ts',
  'Compress': '../../../node_modules/@stacksjs/defaults/app/Middleware/Compress.ts',
  'Cors': '../../../node_modules/@stacksjs/defaults/app/Middleware/Cors.ts',
  'Csrf': '../../../node_modules/@stacksjs/defaults/app/Middleware/Csrf.ts',
  'EnsureEmailIsVerified': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnsureEmailIsVerified.ts',
  'Env': '../../../node_modules/@stacksjs/defaults/app/Middleware/Env.ts',
  'EnvDevelopment': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvDevelopment.ts',
  'EnvLocal': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvLocal.ts',
  'EnvNotDevelopment': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvNotDevelopment.ts',
  'EnvNotLocal': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvNotLocal.ts',
  'EnvNotProduction': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvNotProduction.ts',
  'EnvNotStaging': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvNotStaging.ts',
  'EnvProduction': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvProduction.ts',
  'EnvStaging': '../../../node_modules/@stacksjs/defaults/app/Middleware/EnvStaging.ts',
  'Guest': '../../../node_modules/@stacksjs/defaults/app/Middleware/Guest.ts',
  'Logger': '../../../node_modules/@stacksjs/defaults/app/Middleware/Logger.ts',
  'Maintenance': '../../../node_modules/@stacksjs/defaults/app/Middleware/Maintenance.ts',
  'Permission': '../../../node_modules/@stacksjs/defaults/app/Middleware/Permission.ts',
  'Role': '../../../node_modules/@stacksjs/defaults/app/Middleware/Role.ts',
  'Signed': '../../../node_modules/@stacksjs/defaults/app/Middleware/Signed.ts',
  'Site': '../../../node_modules/@stacksjs/defaults/app/Middleware/Site.ts',
  'Team': '../../../node_modules/@stacksjs/defaults/app/Middleware/Team.ts',
  'Throttle': '../../../node_modules/@stacksjs/defaults/app/Middleware/Throttle.ts',
} as const
