// Generated by ts-cloud for the management dashboard — do not edit.
//
// This is the project's resolved cloud config, inlined so it needs no
// imports on the box. Credentials are deliberately absent.
export default {
  "project": {
    "name": "Wildloop",
    "slug": "wildloop",
    "region": "us-east-1"
  },
  "cloud": {
    "provider": "hetzner",
    "attachTo": "stacks"
  },
  "mode": "server",
  "environments": {
    "production": {
      "type": "production",
      "domain": "wildloop.org"
    }
  },
  "sites": {
    "main": {
      "root": ".",
      "path": "/",
      "domain": "wildloop.org",
      "start": "bun storage/framework/core/buddy/src/cli.ts serve",
      "port": 3049,
      "preStart": [
        "bun install",
        "mkdir -p /var/www/wildloop-shared/database",
        "bun storage/framework/core/buddy/src/cli.ts migrate --force"
      ],
      "env": {
        "API_URL": "",
        "DB_DATABASE_PATH": ""
      }
    },
    "api": {
      "root": ".",
      "start": "bun storage/framework/core/actions/src/serve/api.ts",
      "port": 3050,
      "preStart": [
        "bun install",
        "mkdir -p /var/www/wildloop-shared/database"
      ],
      "env": {
        "HOST": "",
        "APP_ENV": "",
        "DB_DATABASE_PATH": ""
      }
    },
    "www": {
      "domain": "www.wildloop.org",
      "redirect": {
        "to": "https://wildloop.org",
        "status": 301
      }
    }
  },
  "infrastructure": {
    "dns": {
      "provider": "porkbun",
      "domain": "wildloop.org"
    }
  }
}
