/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    achievements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      icon: string
      category: "distance" | "elevation" | "streak" | "social" | "exploration" | "speed"
      metric: "activities" | "distinct_trails" | "total_miles" | "total_elevation" | "territories_conquered" | "territories_defended" | "territories_owned" | "kudos_given" | "streak_days" | "fast_mile"
      target_value: number
      target_unit: "trails" | "miles" | "feet" | "days" | "kudos" | "hours" | "activities" | "territories"
      points: number
      badge_color: "gold" | "silver" | "bronze" | "emerald" | "ruby"
    }
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      trail_id: number
      activity_type: "Trail Run" | "Hike" | "Walk" | "Bike"
      distance: number
      duration: string
      moving_time: string | null
      pace: string
      elevation: number
      kudos_count: number
      notes: string
      gpx_data: string
      splits: string | null
      visibility: "public" | "followers" | "private"
      upload_id: string | null
      recording_source: "web_gps" | "native_gps" | "simulation" | "manual" | "file_import" | "garmin"
      game_mode: "capture" | "free" | "none"
      capture_eligible: number
      integrity_status: "verified" | "unverified" | "rejected"
      integrity_reason: string | null
      completed_at: string
      anomaly_score: number
      integrity_flags: string | null
      track_fingerprint: string | null
      review_state: "none" | "pending" | "cleared" | "upheld"
    }
    activity_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      activity_id: number
      body: string
    }
    analytics_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      category: string
      path: string
      value: number
      currency: string
      properties: string
    }
    auction_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      lot_number: number
      title: string
      description: string
      image_url: string
      category: string
      donor_name: string
      fair_market_value: number
      starting_bid: number
      min_increment: number
      buy_now_price: number
      reserve_price: number
      status: "open" | "closed" | "sold" | "passed"
      closes_at: string
      extension_count: number
      auction_id: number
    }
    auctions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      event_id: number
      title: string
      description: string
      status: "draft" | "preview" | "open" | "closed" | "settled"
      currency: string
      goal_amount: number
      opens_at: string
      closes_at: string
      anti_snipe_minutes: number
      extend_on_bid_window_minutes: number
      max_extensions: number
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      bio: string
      avatar: string
      user_id: number
    }
    automation_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled"
      current_node_id: string
      version: number
      subject_type: string
      subject_id: string
      context: unknown
      idempotency_key: string
      started_at: string
      finished_at: string
      error: string
      team_id: number
      automation_id: number
    }
    automations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      status: "draft" | "active" | "paused" | "archived"
      version: number
      trigger: unknown
      graph: unknown
      published_at: string
      team_id: number
    }
    bids: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      bidder_name: string
      bidder_email: string
      amount: number
      max_amount: number
      status: "leading" | "outbid" | "won" | "lost" | "invalid"
      placed_at: string
      auction_id: number
      auction_item_id: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      position: number
      card_limit: number
      color: string
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      icon: string
      color: string
      position: number
      archived: number
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: "queued" | "deferred" | "sending" | "sent" | "delivered" | "failed" | "undelivered" | "bounced" | "complained" | "suppressed" | "cancelled"
      channel: "email" | "sms" | "push"
      recipient: string
      idempotency_key: string
      provider_message_id: string
      error: string
      sent_at: string
      opened_at: string
      clicked_at: string
      delivered_at: string
      failed_at: string
      segments: number
      cost: number
      metadata: unknown
      team_id: number
      campaign_variant_id: number
    }
    campaign_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      subject: string
      content: unknown
      allocation: number
      sent_count: number
      open_count: number
      click_count: number
      conversion_count: number
      is_winner: number
      team_id: number
      campaign_id: number
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      type: "email" | "sms" | "push" | "social" | "multi-channel"
      status: "draft" | "scheduled" | "sending" | "sent" | "paused" | "cancelled" | "failed" | "active" | "completed" | "archived"
      subject: string
      template: string
      text: string
      content: unknown
      channel_settings: unknown
      segment_definition: unknown
      from_name: string
      from_address: string
      reply_to: string
      timezone: string
      recurrence: string
      experiment_metric: "open_rate" | "click_rate" | "conversion_rate"
      email_list_id: number
      scheduled_at: string
      sent_at: string
      audience_size: number
      sent_count: number
      open_rate: number
      click_rate: number
      conversion_rate: number
      budget: number
      spent: number
      currency: string
      start_date: string
      end_date: string
      team_id: number
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: string
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: number
      board_id: number
      title: string
      description: string
      position: number
      created_by_user_id: number
      due_date: string
      archived: number
      board_column_id: number
      user_id: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: number
      unit_price: number
      total_price: number
      tax_rate: number
      tax_amount: number
      discount_percentage: number
      discount_amount: number
      product_name: string
      product_sku: string
      product_image: string
      notes: string
      cart_id: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "active" | "abandoned" | "converted" | "expired"
      total_items: number
      subtotal: number
      tax_amount: number
      discount_amount: number
      total: number
      expires_at: string
      currency: string
      notes: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      slug: string
      image_url: string
      is_active: number
      parent_category_id: string
      display_order: number
    }
    categorizable_models: {
      // columns
      id: number
      category_id: number
      categorizable_id: number
      categorizable_type: string
      created_at: string
      updated_at: string | null
    }
    challenges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      challenger_id: number
      challenged_id: number
      territory_id: number
      area_at_stake: number
      status: "pending" | "active" | "completed" | "declined"
      winner_id: number | null
      deadline: string
    }
    club_invites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      club_id: number
      invited_by_id: number
      invited_user_id: number | null
      invited_email: string | null
      code: string
      status: "pending" | "accepted" | "revoked" | "expired"
      expires_at: string | null
      accepted_at: string | null
      note: string | null
    }
    club_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      club_id: number
      user_id: number
      role: "owner" | "admin" | "member"
    }
    clubs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      creator_id: number
      name: string
      description: string | null
      location: string | null
      club_type: "Running" | "Hiking" | "Mixed" | "Territory Game"
      is_private: number
      join_policy: "open" | "request" | "invite_only"
      website: string | null
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: string
      author_email: string
      content: string
      body: string
      post_title: string
      status: "pending" | "approved" | "spam" | "trash"
      ip_address: string
      user_agent: string
      is_approved: number
      post_id: number
      user_id: number
    }
    communication_suppressions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: string
      channel: "email" | "sms" | "push"
      reason: "unsubscribe" | "bounce" | "complaint" | "carrier" | "manual" | "legal"
      source: string
      suppressed_at: string
      lifted_at: string
      team_id: number
    }
    consent_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: string
      channel: "email" | "sms" | "push"
      action: "requested" | "granted" | "revoked" | "confirmed" | "suppressed"
      purpose: string
      source: string
      jurisdiction: string
      policy_version: string
      idempotency_key: string
      proof: unknown
      ip_address: string
      occurred_at: string
      team_id: number
    }
    content_reports: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      reporter_id: number
      subject_type: "user" | "activity" | "comment" | "trail_review" | "territory"
      subject_id: number
      reason: "harassment" | "spam" | "unsafe" | "cheating" | "privacy" | "other"
      details: string | null
      status: "open" | "reviewing" | "resolved" | "dismissed"
      resolved_by: number | null
      resolution_notes: string | null
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      description: string
      status: "Active" | "Scheduled" | "Expired"
      is_active: number
      discount_type: "fixed_amount" | "percentage"
      discount_value: number
      min_order_amount: number
      max_discount_amount: number
      free_product_id: string
      usage_limit: number
      usage_count: number
      start_date: string
      end_date: string
      product_id: number
    }
    courier_pings: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      latitude: number
      longitude: number
      heading: number
      speed: number
      accuracy: number
      recorded_at: string
      courier_id: number
      delivery_route_id: number
    }
    couriers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      phone: string
      vehicle_number: string
      license: string
      status: "active" | "on_delivery" | "on_break" | "offline"
      latitude: number
      longitude: number
      heading: number
      speed: number
      last_ping_at: string
      user_id: number
    }
    custom_routes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      name: string
      route_data: string
      distance: number
      elevation: number
      closed_loop: number
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      total_spent: number
      last_order: string
      status: "Active" | "Inactive"
      avatar: string
      user_id: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      courier: string
      vehicle: string
      stops: number
      delivery_time: number
      total_distance: number
      last_active: number
      status: "planned" | "active" | "completed" | "cancelled"
      started_at: string
      completed_at: string
      courier_id: number
    }
    delivery_stops: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      sequence: number
      status: "pending" | "en_route" | "arrived" | "completed" | "failed" | "skipped"
      address: string
      latitude: number
      longitude: number
      recipient_name: string
      recipient_phone: string
      eta_at: string
      notified_nearby_at: string
      arrived_at: string
      completed_at: string
      notes: string
      type: "pickup" | "dropoff"
      delivery_route_id: number
      order_id: number
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commit_hash: string
      commit_message: string
      branch: string
      status: string
      environment: string
      duration: number
      author: string
      url: string
      error_log: string
    }
    device_push_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      token: string
      platform: "ios" | "android"
      device_id: string | null
      environment: "development" | "production"
      last_seen_at: string
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      download_limit: number
      expiry_days: number
      requires_login: number
      automatic_delivery: number
      status: "active" | "inactive"
    }
    email_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      message_id: string
      recipient: string
      subject: string
      provider: string
      success: number
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      subscribed_at: string
      unsubscribed_at: string
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      subscriber_count: number
      active_count: number
      unsubscribed_count: number
      bounced_count: number
      status: "active" | "inactive" | "archived"
      is_public: number
      double_opt_in: number
    }
    email_suppressions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: string
      type: "bounce" | "complaint" | "unsubscribe" | "manual"
      reason: string
    }
    email_webhook_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: "mailgun" | "postmark" | "ses" | "sendgrid"
      event_id: string
      processed_at: string
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: string
      message: string
      stack: string
      status: number
      additional_info: string
    }
    event_entrants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      event_id: number
      user_id: number
      bib: string | null
      status: "registered" | "running" | "timed_out" | "withdrawn" | "dnf" | "winner"
      yards_completed: number
      last_lap_at: string | null
      exit_note: string | null
    }
    event_laps: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      event_id: number
      user_id: number
      yard_number: number
      started_at: string | null
      finished_at: string
      duration_seconds: number
      distance: number | null
      activity_id: number | null
      source: "recorder" | "manual" | "import"
    }
    events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      host_id: number
      club_id: number | null
      trail_id: number | null
      name: string
      description: string | null
      location: string | null
      event_type: "backyard" | "race" | "group_run" | "time_trial"
      status: "scheduled" | "live" | "finished" | "cancelled"
      visibility: "public" | "club" | "private"
      loop_distance: number
      loop_route: string | null
      yard_minutes: number
      start_time: string
      max_yards: number | null
      winner_id: number | null
    }
    failed_jobs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      connection: string
      queue: string
      payload: string
      exception: string
      attempts: number
      max_attempts: number
      duration_ms: number
      failed_at: string
    }
    follows: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      follower_id: number
      following_id: number
    }
    form_fields: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      label: string
      type: "text" | "textarea" | "email" | "phone" | "select" | "checkbox" | "radio" | "date" | "file" | "currency" | "section_break"
      required: number
      position: number
      width: "full" | "half"
      options: unknown
      conditions: unknown
      form_id: number
    }
    form_submissions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      data: unknown
      email: string
      name: string
      status: "pending_payment" | "complete" | "spam"
      amount_cents: number
      payment_intent_id: string
      ip: string
      submitted_at: string
      form_id: number
      site_id: number
    }
    forms: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      handle: string
      status: "draft" | "active" | "closed"
      settings: unknown
      site_id: number
    }
    garmin_activity_imports: {
      // columns
      id: number
      user_id: number
      summary_id: string
      activity_id: number | null
      created_at: string
    }
    garmin_connections: {
      // columns
      id: number
      user_id: number
      garmin_user_id: string
      access_token: string
      refresh_token: string | null
      expires_at: number | null
      scope: string | null
      last_sync_at: string | null
      created_at: string
      updated_at: string | null
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      initial_balance: number
      current_balance: number
      currency: string
      status: "ACTIVE" | "USED" | "EXPIRED" | "DEACTIVATED"
      purchaser_id: string
      recipient_email: string
      recipient_name: string
      personal_message: string
      is_digital: number
      is_reloadable: number
      is_active: number
      expiry_date: string
      last_used_date: string
      template_id: string
      customer_id: number
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: string
      payload: string
      attempts: number
      available_at: number
      reserved_at: number
    }
    kudos: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      giver_id: number
      user_id: number
      activity_id: number
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      color: string
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      template: "Standard License" | "Premium License" | "Enterprise License"
      expiry_date: string
      status: "active" | "inactive" | "unassigned"
      customer_id: number
      product_id: number
      order_id: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: number
      type: "warning" | "error" | "info" | "success"
      source: "file" | "cli" | "system"
      message: string
      project: string
      stacktrace: string
      file: string
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: string
      points: number
      source: string
      source_reference_id: string
      description: string
      expiry_date: string
      is_used: number
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      points_required: number
      reward_type: string
      discount_percentage: number
      free_product_id: string
      is_active: number
      expiry_days: number
      image_url: string
      product_id: number
    }
    magic_link_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: string
      token: string
      expires_at: string
      consumed_at: string
      redirect_to: string
      site_id: number
      user_id: number
    }
    mail_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      mailbox: string
      account_name: string
      signature: string
      display_density: "comfortable" | "default" | "compact"
      theme: "light" | "dark" | "system"
      language: "en" | "fr" | "de" | "es" | "ja"
      default_reply_behavior: "reply" | "replyAll"
      send_and_archive: number
      auto_advance: "newer" | "older" | "back"
      desktop_notifications: number
      notification_sound: "default" | "subtle" | "none"
      notification_preview: number
      filters: string
      blocked_senders: string
      labels: string
      load_remote_images: number
      show_external_content: number
      vacation_enabled: number
      vacation_start_date: string
      vacation_end_date: string
      vacation_subject: string
      vacation_message: string
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: string
      description: string
      country: string
      featured: number
    }
    menu_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      label: string
      url: string
      target: "_self" | "_blank"
      parent_id: number
      position: number
      visibility: "public" | "auth"
      menu_id: number
      page_id: number
    }
    menus: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      handle: string
      name: string
      site_id: number
    }
    notification_deliveries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      channel: "email" | "sms" | "chat" | "database" | "push" | "broadcast"
      recipient: string
      subject: string
      body: string
      status: "pending" | "sent" | "delivered" | "failed"
      error: string
      metadata: string
      sent_at: string
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      data: string
      read_at: string
      user_id: number
    }
    order_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      order_id: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: number
      price: number
      special_instructions: string
      order_id: number
      product_id: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: string
      total_amount: number
      currency: string
      tax_amount: number
      discount_amount: number
      delivery_fee: number
      tip_amount: number
      order_type: string
      delivery_address: string
      special_instructions: string
      estimated_delivery_time: string
      tracking_token: string
      delivery_latitude: number
      delivery_longitude: number
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    page_revisions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      revision: number
      title: string
      blocks: unknown
      meta_description: string
      note: string
      page_id: number
      author_id: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      path: string
      parent_id: number
      template: string
      blocks: unknown
      meta_description: string
      status: "draft" | "published" | "scheduled" | "archived"
      scheduled_at: string
      views: number
      published_at: string
      conversions: number
      author_id: number
      site_id: number
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      last_four: number
      brand: string
      exp_month: number
      exp_year: number
      is_default: number
      provider_id: string
      user_id: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      key: string
      unit_price: number
      status: string
      image: string
      provider_id: string
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      amount: number
      type: string
      provider_id: string
      user_id: number
      payment_method_id: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      method: "cash" | "creditCard" | "debitCard" | "paypal" | "applePay" | "googlePay" | "bankTransfer" | "giftCard"
      status: "pending" | "processing" | "completed" | "failed" | "refunded" | "partiallyRefunded" | "succeeded"
      currency: string
      reference_number: string
      card_last_four: string
      card_brand: string
      billing_email: string
      transaction_id: string
      payment_provider: string
      refund_amount: number
      notes: string
      order_id: number
      customer_id: number
    }
    pledges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      donor_name: string
      donor_email: string
      amount: number
      level: string
      status: "pending" | "confirmed" | "cancelled"
      auction_id: number
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      poster: string
      content: string
      excerpt: string
      focus_keyword: string
      meta_description: string
      canonical_url: string
      views: number
      published_at: string
      status: "published" | "draft" | "archived"
      is_featured: number
      author_id: number
      site_id: number
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      mac_address: string
      location: string
      terminal: string
      status: "online" | "offline" | "warning"
      last_ping: number
      print_count: number
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      abbreviation: string
      type: string
      description: string
      is_default: number
      product_id: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: string
      type: string
      description: string
      options: string
      status: "active" | "inactive" | "draft"
      product_id: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      price: number
      image_url: string
      is_available: number
      inventory_count: number
      preparation_time: number
      allergens: string
      nutritional_info: string
      category_id: number
      manufacturer_id: number
    }
    query_logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      query: string
      normalized_query: string
      duration: number
      connection: string
      status: "completed" | "failed" | "slow"
      error: string
      executed_at: string
      bindings: string
      trace: string
      model: string
      method: string
      file: string
      line: number
      memory_usage: number
      rows_affected: number
      transaction_id: string
      tags: string
      affected_tables: string
      indexes_used: string
      missing_indexes: string
      explain_plan: string
      optimization_suggestions: string
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: string
      document: string
      timestamp: string
      status: "success" | "failed" | "warning"
      size: number
      pages: number
      duration: number
      metadata: string
      print_device_id: number
    }
    redirects: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      from_path: string
      to_path: string
      status_code: number
      source: "slug-change" | "manual"
      site_id: number
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: string
      type: string
      status: string
      notes: string
      downloads: number
      author: string
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD"
      path: string
      status_code: number
      duration_ms: number
      ip_address: string
      memory_usage: number
      user_agent: string
      error_message: string
    }
    route_efforts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      trail_id: number
      user_id: number
      activity_id: number | null
      style: "supported" | "self_supported" | "unsupported"
      category: "mens" | "womens" | "nonbinary"
      direction: "standard" | "reverse" | "yo_yo"
      team_size: number
      status: "in_progress" | "dnf" | "pending" | "verified" | "rejected"
      started_at: string
      finished_at: string | null
      elapsed_seconds: number | null
      evidence_url: string | null
      gpx_url: string | null
      tracker_url: string | null
      trip_report: string | null
      reviewed_by: number | null
      reviewed_at: string | null
      review_note: string | null
    }
    saved_trails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      trail_id: number
      notes: string | null
      want_to_visit: number
      has_visited: number
    }
    sender_domains: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      domain: string
      status: "pending" | "verified" | "failed" | "disabled"
      selector: string
      dns_records: unknown
      verified_at: string
      last_checked_at: string
      team_id: number
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      base_rate: number
      free_shipping: number
      status: "active" | "inactive" | "draft"
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: number
      weight_to: number
      rate: number
      shipping_method_id: number
      shipping_zone_id: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      countries: string
      regions: string
      postal_codes: string
      status: "active" | "inactive" | "draft"
      shipping_method_id: number
    }
    site_domains: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      domain: string
      is_primary: number
      verified_at: string
      ssl_status: "pending" | "issued" | "failed"
      site_id: number
    }
    sites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      subdomain: string
      status: "active" | "suspended" | "archived"
      settings: unknown
      timezone: string
      team_id: number
    }
    sms_opt_outs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      phone: string
      reason: string
      opted_out_at: string
    }
    social_accounts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      provider_user_id: string
      provider_email: string
      user_id: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: string
      platform: "twitter" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube"
      status: "draft" | "scheduled" | "published" | "failed"
      scheduled_at: string
      published_at: string
      likes: number
      shares: number
      comments: number
      reach: number
      image_url: string
      external_id: string
      user_id: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      source: string
      subscriber_id: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      unsubscribed_at: string
      user_id: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      plan: string
      provider_id: string
      provider_status: string
      unit_price: number
      provider_type: string
      provider_price_id: string
      quantity: number
      trial_ends_at: string
      ends_at: string
      last_used_at: string
      user_id: number
    }
    taggable_models: {
      // columns
      id: number
      tag_id: number
      taggable_id: number
      taggable_type: string
      created_at: string
      updated_at: string | null
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      color: string
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      rate: number
      type: string
      country: string
      region: "North America" | "South America" | "Europe" | "Asia" | "Africa" | "Oceania" | "Antarctica"
      status: "active" | "inactive"
      is_default: number
      code: string
      exemptible: number
    }
    team_invitations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      email: string
      role: "admin" | "member" | "viewer"
      token_hash: string
      pending_key: string
      invited_by_user_id: number
      accepted_by_user_id: number
      status: "pending" | "accepted" | "revoked" | "expired"
      delivery_status: "pending" | "sent" | "failed"
      delivery_error: string
      expires_at: string
      delivered_at: string
      accepted_at: string
    }
    team_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      user_id: number
      role: "owner" | "admin" | "member" | "viewer"
      status: "active" | "suspended"
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      member_count: number
      status: string
    }
    territories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      activity_id: number
      parent_territory_id: number | null
      name: string | null
      polygon_data: string
      bounding_box: string | null
      min_lat: number | null
      min_lng: number | null
      max_lat: number | null
      max_lng: number | null
      center_lat: number
      center_lng: number
      area_size: number
      perimeter: number | null
      status: "active" | "contested" | "expired"
      conquest_count: number
      claimed_at: string
      last_activity_at: string | null
    }
    territory_activity_resolutions: {
      // columns
      id: number
      activity_id: number
      territory_id: number
      outcome: string
      created_at: string
    }
    territory_histories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      territory_id: number
      user_id: number
      activity_id: number
      previous_owner_id: number | null
      event_type: "claimed" | "conquered" | "split" | "defended" | "contested" | "expired"
      area_at_event: number | null
      previous_ownership_duration: number | null
      notes: string | null
      new_territory_id: number | null
    }
    territory_stats: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      total_territories_owned: number
      total_area_owned: number
      territories_claimed: number
      territories_conquered: number
      territories_lost: number
      territories_defended: number
      longest_ownership_days: number
      largest_territory_area: number
      weekly_rank: number | null
      all_time_rank: number | null
      xp: number
    }
    trail_ingest_shards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      shard_key: string
      source: "osm" | "usfs" | "nps"
      cursor: string
      status: "pending" | "running" | "done" | "failed"
      attempts: number
      features_seen: number
      trails_imported: number
      trails_updated: number
      last_error: string
      started_at: string
      completed_at: string
    }
    trail_reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      trail_id: number
      rating: number
      title: string | null
      content: string
      visit_date: string | null
      conditions: "excellent" | "good" | "fair" | "poor" | "muddy" | "icy" | null
      helpful_count: number
      photos: string | null
    }
    trails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      location: string
      distance: number
      elevation: number
      difficulty: "easy" | "moderate" | "hard"
      rating: number
      review_count: number
      estimated_time: string
      image: string
      tags: string
      latitude: number
      longitude: number
      description: string
      geometry: string
      source: "osm" | "usfs" | "nps" | "manual"
      source_id: string
      source_url: string
      synced_at: string
      country: string
      state: string
      state_name: string
      managed_by: string
      min_lat: number
      max_lat: number
      min_lng: number
      max_lng: number
      route_type: "loop" | "out-and-back" | "point-to-point" | "network"
      surface: string
      elevation_high: number
      allowed_uses: string
      dogs_allowed: number
      wheelchair_accessible: number
      national_trail: number
    }
    trails_fts: {
      // columns
      name: unknown
      location: unknown
      state_name: unknown
    }
    trails_fts_config: {
      // columns
      k: unknown
      v: unknown
    }
    trails_fts_data: {
      // columns
      id: number
      block: Uint8Array | null
    }
    trails_fts_docsize: {
      // columns
      id: number
      sz: Uint8Array | null
    }
    trails_fts_idx: {
      // columns
      segid: unknown
      term: unknown
      pgno: unknown
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      status: string
      payment_method: string
      payment_details: string
      transaction_reference: string
      loyalty_points_earned: number
      loyalty_points_redeemed: number
      order_id: number
    }
    usage_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      meter: "contacts" | "email_sends" | "sms_segments" | "ai_generations" | "storage_bytes"
      quantity: number
      idempotency_key: string
      metadata: unknown
      occurred_at: string
      team_id: number
    }
    user_achievements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      achievement_id: number
      progress: number
      completed_at: string | null
      is_complete: number
    }
    user_blocks: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      blocker_id: number
      blocked_id: number
    }
    user_notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient_id: number
      actor_id: number
      actor_name: string
      type: "kudos" | "comment" | "follow" | "conquest" | "conquest_attack" | "conquest_defend" | "conquest_win" | "achievement" | "challenge" | "record"
      body: string
      link: string
      read: number
    }
    user_privacy_settings: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      default_activity_visibility: "public" | "followers" | "private"
      hide_start_end_meters: number
      home_lat: number | null
      home_lng: number | null
      home_radius_meters: number
      exclude_home_from_game: number
      show_precise_territories: number
    }
    user_stats: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      total_distance: number
      total_time: string
      total_elevation: number
      trails_completed: number
      current_streak: number
      longest_streak: number
      weekly_rank: number
      total_activities: number
      total_kudos_received: number
      total_kudos_given: number
      user_id: number
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_verified_at: string | null
      password_changed_at: string | null
      two_factor_secret: string | null
      two_factor_enabled: number | null
      two_factor_last_used_step: number | null
      stripe_id: string | null
      name: string
      email: string
      password: string
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      quantity: number
      notification_preference: "sms" | "email" | "both"
      source: string
      notes: string
      status: "waiting" | "purchased" | "notified" | "cancelled"
      notified_at: string
      purchased_at: string
      cancelled_at: string
      product_id: number
      customer_id: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      party_size: number
      check_in_time: string
      table_preference: "indoor" | "bar" | "booth" | "no_preference"
      status: "waiting" | "seated" | "cancelled" | "no_show"
      quoted_wait_time: number
      actual_wait_time: number
      queue_position: number
      seated_at: string
      no_show_at: string
      cancelled_at: string
      customer_id: number
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: "disconnection" | "error" | "success"
      socket: string
      details: string
      time: number
    }
  }
}

export {}
