import { describe, expect, it } from 'bun:test'
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  conflictingProviders,
  iosShortcutsSwift,
  shortcutsSourcePath,
  swiftPhraseLiteral,
  swiftIdentifier,
  swiftString,
  writeIosShortcuts,
} from '../../scripts/generate-ios-shortcuts'
import { APP_SHORTCUTS } from '../../resources/functions/app-shortcuts'

const options = { appName: 'WildLoop', scheme: 'wildloop' }

describe('Swift building blocks', () => {
  it('escapes what would end a string literal', () => {
    expect(swiftString('Trails "near" me')).toBe('"Trails \\"near\\" me"')
    expect(swiftString('back\\slash')).toBe('"back\\\\slash"')
  })

  it('turns an id into a type name', () => {
    expect(swiftIdentifier('trails-near-me')).toBe('TrailsNearMe')
    expect(swiftIdentifier('view_stats')).toBe('ViewStats')
    expect(swiftIdentifier('3d-view')).toBe('Shortcut3dView')
  })

  it('carries the application-name token as a real interpolation', () => {
    // One backslash, not two: escaped, the processor rejects the utterance.
    expect(swiftPhraseLiteral('Show my stats in WildLoop', 'WildLoop')).toBe('"Show my stats in \\(.applicationName)"')
    expect(swiftPhraseLiteral('Show my stats', 'WildLoop')).toBe('"Show my stats with \\(.applicationName)"')
  })

  it('still escapes the text around the token', () => {
    expect(swiftPhraseLiteral('Open "WildLoop" now', 'WildLoop')).toBe('"Open \\"\\(.applicationName)\\" now"')
  })
})

describe('the generated Swift', () => {
  const swift = iosShortcutsSwift(options)

  it('declares one intent per shortcut and one provider', () => {
    expect(swift).toContain('struct OpenFavoritesIntent: AppIntent')
    expect(swift).toContain('struct OpenTrailsNearMeIntent: AppIntent')
    expect(swift).toContain('struct OpenViewStatsIntent: AppIntent')
    expect(swift.match(/AppShortcutsProvider/g)).toHaveLength(1)
    expect(swift).toContain('struct WildLoopAppShortcuts: AppShortcutsProvider')
  })

  it('opens each shortcut’s own deep link', () => {
    expect(swift).toContain('URL(string: "wildloop://profile?tab=saved")')
    expect(swift).toContain('URL(string: "wildloop://trails?near=me")')
    expect(swift).toContain('URL(string: "wildloop://stats")')
    // Awaited inside perform(): the async overload is what an async context
    // resolves to, and Xcode rejects it bare.
    expect(swift.match(/await UIApplication\.shared\.open\(url\)/g)).toHaveLength(APP_SHORTCUTS.length)
  })

  it('brings the app forward, since the link is what places it', () => {
    expect(swift.match(/static var openAppWhenRun: Bool = true/g)).toHaveLength(APP_SHORTCUTS.length)
  })

  it('offers every shortcut to Spotlight, with its title and symbol', () => {
    for (const shortcut of APP_SHORTCUTS) {
      expect(swift).toContain(`shortTitle: "${shortcut.title}"`)
      expect(swift).toContain(`systemImageName: "${shortcut.symbol}"`)
    }
    expect(swift.match(/AppShortcut\(\n {12}intent:/g)).toHaveLength(APP_SHORTCUTS.length)
  })

  it('states the iOS version every one of these types needs', () => {
    // 16.4, not the app's 16.0 deployment target: the AppShortcut initializer
    // that takes shortTitle and systemImageName is 16.4+, and a 16.0
    // attribute over it does not compile.
    expect(swift.match(/@available\(iOS 16\.4, \*\)/g)).toHaveLength(APP_SHORTCUTS.length + 1)
    expect(swift).not.toContain('@available(iOS 16.0')
    expect(swift).toContain('import AppIntents')
    expect(swift).toContain('import UIKit')
  })

  it('follows the scheme the build registered', () => {
    expect(iosShortcutsSwift({ appName: 'WildLoop', scheme: 'wildloop-dev' }))
      .toContain('URL(string: "wildloop-dev://stats")')
  })

  it('never doubles the backslash in an utterance, which fails metadata export', () => {
    // `\\(.applicationName)` in the file is a literal, not an interpolation,
    // and appintentsmetadataprocessor rejects the whole target for it.
    expect(swift.includes('\\\\(.applicationName)')).toBe(false)
    expect(swift.split('\\(.applicationName)').length - 1).toBe(APP_SHORTCUTS.length)
  })

  it('says it is generated, and where from', () => {
    expect(swift.startsWith('// Generated by scripts/generate-ios-shortcuts.ts')).toBe(true)
    expect(swift).toContain('resources/functions/app-shortcuts.ts')
  })
})

describe('writing into a project', () => {
  async function project(): Promise<string> {
    const dir = await mkdtemp(join(tmpdir(), 'wildloop-ios-'))
    await mkdir(join(dir, 'Sources'), { recursive: true })
    return dir
  }

  it('lands beside the app’s other sources', async () => {
    const dir = await project()
    const path = await writeIosShortcuts(dir, options)

    expect(path).toBe(shortcutsSourcePath(dir, 'WildLoop'))
    expect(path.endsWith('Sources/WildLoopAppShortcuts.swift')).toBe(true)
    expect(await Bun.file(path).text()).toContain('AppShortcutsProvider')
  })

  it('notices another provider, which iOS would leave ambiguous', async () => {
    const dir = await project()
    const ours = await writeIosShortcuts(dir, options)
    expect(await conflictingProviders(dir, ours)).toEqual([])

    const theirs = join(dir, 'Sources', 'CraftAppExtensions.swift')
    await writeFile(theirs, 'struct CraftShortcuts: AppShortcutsProvider {}\n')
    expect(await conflictingProviders(dir, ours)).toEqual([theirs])
  })
})

describe('what it deliberately leaves to Craft', () => {
  it('declares no quick-action handler, which Craft\u2019s own delegate already has', () => {
    // The simulator build rejected a second one: "invalid redeclaration of
    // 'application(_:performActionFor:completionHandler:)'".
    const swift = iosShortcutsSwift(options)
    expect(swift).not.toContain('performActionFor')
    expect(swift).not.toContain('extension')
  })
})
