import { describe, expect, it } from 'bun:test'
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  conflictingProviders,
  findDelegateType,
  iosShortcutsSwift,
  shortcutsSourcePath,
  sirifyPhrase,
  swiftIdentifier,
  swiftString,
  writeIosShortcuts,
} from '../../scripts/generate-ios-shortcuts'
import { APP_SHORTCUTS } from '../../resources/functions/app-shortcuts'

const options = { appName: 'WildLoop', scheme: 'wildloop' }

describe('Swift building blocks', () => {
  it('escapes what would end a string literal', () => {
    expect(swiftString('Trails "near" me')).toBe('"Trails \\"near\\" me"')
    expect(swiftString('back\\slash')).toBe('"back\\\\slash"')
  })

  it('turns an id into a type name', () => {
    expect(swiftIdentifier('trails-near-me')).toBe('TrailsNearMe')
    expect(swiftIdentifier('view_stats')).toBe('ViewStats')
    expect(swiftIdentifier('3d-view')).toBe('Shortcut3dView')
  })

  it('carries the application-name token every phrase needs', () => {
    expect(sirifyPhrase('Show my stats in WildLoop', 'WildLoop')).toBe('Show my stats in \\(.applicationName)')
    // A phrase that never names the app still has to carry the token.
    expect(sirifyPhrase('Show my stats', 'WildLoop')).toBe('Show my stats with \\(.applicationName)')
  })
})

describe('the generated Swift', () => {
  const swift = iosShortcutsSwift(options)

  it('declares one intent per shortcut and one provider', () => {
    expect(swift).toContain('struct OpenFavoritesIntent: AppIntent')
    expect(swift).toContain('struct OpenTrailsNearMeIntent: AppIntent')
    expect(swift).toContain('struct OpenViewStatsIntent: AppIntent')
    expect(swift.match(/AppShortcutsProvider/g)).toHaveLength(1)
    expect(swift).toContain('struct WildLoopAppShortcuts: AppShortcutsProvider')
  })

  it('opens each shortcut’s own deep link', () => {
    expect(swift).toContain('URL(string: "wildloop://profile?tab=saved")')
    expect(swift).toContain('URL(string: "wildloop://trails?near=me")')
    expect(swift).toContain('URL(string: "wildloop://stats")')
    // Awaited inside perform(): the async overload is what an async context
    // resolves to, and Xcode rejects it bare.
    expect(swift.match(/await UIApplication\.shared\.open\(url\)/g)).toHaveLength(APP_SHORTCUTS.length)
  })

  it('brings the app forward, since the link is what places it', () => {
    expect(swift.match(/static var openAppWhenRun: Bool = true/g)).toHaveLength(APP_SHORTCUTS.length)
  })

  it('offers every shortcut to Spotlight, with its title and symbol', () => {
    for (const shortcut of APP_SHORTCUTS) {
      expect(swift).toContain(`shortTitle: "${shortcut.title}"`)
      expect(swift).toContain(`systemImageName: "${shortcut.symbol}"`)
    }
    expect(swift.match(/AppShortcut\(\n {12}intent:/g)).toHaveLength(APP_SHORTCUTS.length)
  })

  it('states the iOS version every one of these types needs', () => {
    // 16.4, not the app's 16.0 deployment target: the AppShortcut initializer
    // that takes shortTitle and systemImageName is 16.4+, and a 16.0
    // attribute over it does not compile.
    expect(swift.match(/@available\(iOS 16\.4, \*\)/g)).toHaveLength(APP_SHORTCUTS.length + 1)
    expect(swift).not.toContain('@available(iOS 16.0')
    expect(swift).toContain('import AppIntents')
    expect(swift).toContain('import UIKit')
  })

  it('follows the scheme the build registered', () => {
    expect(iosShortcutsSwift({ appName: 'WildLoop', scheme: 'wildloop-dev' }))
      .toContain('URL(string: "wildloop-dev://stats")')
  })

  it('says it is generated, and where from', () => {
    expect(swift.startsWith('// Generated by scripts/generate-ios-shortcuts.ts')).toBe(true)
    expect(swift).toContain('resources/functions/app-shortcuts.ts')
  })
})

describe('writing into a project', () => {
  async function project(): Promise<string> {
    const dir = await mkdtemp(join(tmpdir(), 'wildloop-ios-'))
    await mkdir(join(dir, 'Sources'), { recursive: true })
    return dir
  }

  it('lands beside the app’s other sources', async () => {
    const dir = await project()
    const path = await writeIosShortcuts(dir, options)

    expect(path).toBe(shortcutsSourcePath(dir, 'WildLoop'))
    expect(path.endsWith('Sources/WildLoopAppShortcuts.swift')).toBe(true)
    expect(await Bun.file(path).text()).toContain('AppShortcutsProvider')
  })

  it('notices another provider, which iOS would leave ambiguous', async () => {
    const dir = await project()
    const ours = await writeIosShortcuts(dir, options)
    expect(await conflictingProviders(dir, ours)).toEqual([])

    const theirs = join(dir, 'Sources', 'CraftAppExtensions.swift')
    await writeFile(theirs, 'struct CraftShortcuts: AppShortcutsProvider {}\n')
    expect(await conflictingProviders(dir, ours)).toEqual([theirs])
  })
})

describe('routing a tapped home-screen shortcut', () => {
  it('finds the delegate Craft installs', () => {
    expect(findDelegateType([
      'import SwiftUI\nfinal class CraftAppDelegate: NSObject, UIApplicationDelegate, UNUserNotificationCenterDelegate {\n}',
    ])).toBe('CraftAppDelegate')
  })

  it('says so when the project has none in that shape', () => {
    expect(findDelegateType(['struct CraftApp: App {}'])).toBeNull()
    expect(findDelegateType([])).toBeNull()
  })

  it('handles the tap against the delegate it was given', () => {
    const swift = iosShortcutsSwift({ ...options, delegateType: 'CraftAppDelegate' })

    expect(swift).toContain('extension CraftAppDelegate {')
    expect(swift).toContain('performActionFor shortcutItem: UIApplicationShortcutItem')
    // Written out rather than inferred: a change that stops this being a
    // protocol witness should fail the build, not go quiet.
    expect(swift).toContain('@objc')
    expect(swift).toContain('shortcutItem.userInfo?["url"] as? String')
    expect(swift).toContain('completionHandler(true)')
    // The delegate method is not async, so the call there takes the
    // completion-handler overload and must NOT be awaited.
    expect(swift.split('extension CraftAppDelegate')[1]).toContain('\n        UIApplication.shared.open(url)')
  })

  it('leaves the app’s own sources alone when there is no delegate', () => {
    const swift = iosShortcutsSwift(options)
    expect(swift).not.toContain('extension')
    expect(swift).not.toContain('performActionFor')
  })

  it('picks the delegate out of the project it is writing into', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'wildloop-ios-'))
    await mkdir(join(dir, 'Sources'), { recursive: true })
    await writeFile(
      join(dir, 'Sources', 'WildLoopApp.swift'),
      'final class CraftAppDelegate: NSObject, UIApplicationDelegate {\n}\n',
    )

    const path = await writeIosShortcuts(dir, options)
    expect(await Bun.file(path).text()).toContain('extension CraftAppDelegate {')
  })
})
